name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
  - title: '📝 Documentation'
    labels:
      - 'kind/documentation'
  - title: '🔨 Maintenance'
    labels:
      - 'kind/maintenance'
version-resolver:
  major:
    labels:
      - 'next-version/major'
  minor:
    labels:
      - 'next-version/minor'
  patch:
    labels:
      - 'next-version/patch'
  default: minor
template: |
  $CHANGES
