name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'kind/enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'kind/bug'
  - title: '📝 Documentation'
    labels:
      - 'kind/documentation'
  - title: '🔨 Maintenance'
    labels:
      - 'kind/maintenance'
version-resolver:
  default: minor
template: |
  $CHANGES
